// src/lib/components/header/Header.svelte
<script lang="ts">
	import EchoLogo from '$lib/assets/images/echo-logo.png';
	import { getAuthState } from '$lib/contexts/auth-context';
	import HeaderLink from './HeaderLink.svelte';
	import SignOutButton from './SignOutButton.svelte';
	import ThemeToggle from './ThemeToggle.svelte';

	let authState = getAuthState();
</script>

<div class="border-b-2 mb-8">
	<header class="flex justify-between items-center max-w-screen-lg mx-auto py-2 px-4">
		<div>
			<a href="/">
				<img class="h-14 w-14" src={EchoLogo} alt="Echo Logo" />
			</a>
		</div>

		<menu class="flex">
			{#if !authState.isAuthenticated}
				<HeaderLink href="/logg-inn">Logg inn</HeaderLink>
			{/if}

			{#if authState.isAuthenticated}
				<HeaderLink href="/profil">Profil</HeaderLink>
				<SignOutButton />
			{/if}
			<ThemeToggle />
		</menu>
	</header>
</div>

// src/components/header.tsx
import Image from "next/image";
import Link from "next/link";

import { auth } from "@/server/auth";
import { LogInButton } from "./log-in-button";
import { LogOutButton } from "./log-out-button";

export const Header = async () => {
  const { user } = await auth();

  return (
    <div className="mb-10 border-b">
      <header className="container flex items-center justify-between p-4">
        <div>
          <Link href="/">
            <Image src="/images/echo_liggende_variant.png" alt="Logo" width={180} height={180} />
          </Link>
        </div>

        <div>
          <ul className="flex items-center gap-4">
            {user ? (
              <>
                <li>
                  <Link className="hover:text-blue-500 hover:underline" href="/profil">
                    Profil
                  </Link>
                </li>
                <li>
                  <LogOutButton />
                </li>
              </>
            ) : (
              <>
                <li>
                  <LogInButton />
                </li>
              </>
            )}
          </ul>
        </div>
      </header>
    </div>
  );
};
